apiVersion: v1
kind: Service
metadata:
  name: sampleapp-service
  labels:
    app: sampleapp
spec:
  selector:
    app: sampleapp
  ports:
  - protocol: TCP
    port: 80  # Port exposed by the service
    targetPort: 80  # Port on the container
  type: NodePort  # Use ClusterIP for internal access, NodePort or LoadBalancer for external access
